### PR TITLE
Move the heavy browser dependencies to a 'browser' extra

### PR DESCRIPTION
**Pull request by jamadden**
And make the tests that rely on them conditional. Ensure that the ZCML can be executed either way, though. Add tox and Travis environments to be sure this is exercised.

Previously, a zope.mimetype install was very large, unconditionally pulling in zope.browser, zope.publisher and zope.formlib, which in turn pulled in zope.browserpage, zope.datetime, zope.pagetemplate, zope.tales, zope.tal, zope.browserresource, zope.traversing, transaction, and six, possibly among others. Now, those things are opt-in, leaving the default install about 10 packages smaller.

Also some gardening things:

- Rename remaining .txt to .rst
- Drop support for Python 3.3
- Badges in readme.
- setup.cfg for universal wheels.
- Update .travis.yml with current PyPy (grabbed from zope.viewlet)
- Update tox.ini to include the coverage environment too.

### CODE REVIEW

**Comment by jamadden** [comment]
My use case is that we have a library we use with Pyramid for handling JSON input and output. It's based on mime types, and so we want to use the IContentTypeAware interface (among others) that this package provides. That library doesn't use anything from zope.browser, and [we'd like to trim our dependencies](https://github.com/NextThought/nti.externalization/issues/20), so making these things optional here seemed like a reasonable thing to do.

**Comment by jamadden** [comment]
Thank you!

A PyPI release would be nice, when convenient.

**Comment by tseaver** [comment]
*Poof!*  You are a PyPI owner.

**Comment by jamadden** [comment]
Neat! Thanks again.

**Pull request merged**
